baseURL = "https://example.com"

# set your your own ga token here.
googleAnalytics = ""

languageCode = "en-us"

# for using avicenna you need to set the themes to 'avicenna'
enableEmoji = true
theme = "avicenna"

# This is your page title, it appears in your tab
title = "Stanley Z. Hua"

# number of posts to show on the blog page
paginate = 10

[markup]
[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 1

[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true

[params]
# it is used for the copy-right section of your page
name = "Stanley Hua"
