---
title: Recipe Scraping
author: ''
date: ''
slug: recipe-scraping
categories:
  - R
tags:
  - Data Wrangling
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r setup,include=FALSE}
library(rvest)
library(shiny)
library(flexdashboard)
```

```{r, echo=FALSE}
create_text<-function(input_url){
  website<-function(link=input_url){
    webpage<-read_html(link)
    recipefor_html<-html_nodes(webpage,'.heading-content')    #change if using different website
    recipefor<-html_text(recipefor_html)
    recipefor<<-recipefor[4]                                   #change if using different website
    
    #Fetch directions
    directions_html<-html_nodes(webpage,".instructions-section")
    directions_unparsed<-html_text(directions_html)
    directions<<-parse_block(directions_unparsed,"Step")
    
    #Fetch ingredients
    ingredients_html<-html_nodes(webpage,".ingredients-item-name")
    ingredients<<-trimws(html_text(ingredients_html))
  }
  
  #Helper Function
  parse_block<-function(str_block,separation){
    block<-trimws(str_block)
    chunks<-unlist(strsplit(block,separation))
    
    pieces<-character()
    
    for(chunk in chunks){
      unprocessed_spaces<-unlist(strsplit(chunk,"\n"))
      for(proc in unprocessed_spaces){
        line<-trimws(proc)
        if(nchar(line)>2 && line!="Advertisement"){        #note 2 is chosen arbitrarily to avoid stand-alone numbers
          pieces<-c(pieces,line)
        }
      }
    }
    pieces
  }
  
  website(input_url)
  
  # Recipe Title
  header<-sprintf("### %s\n\n",recipefor)
  
  # Instructions
  instructions<-"### Directions\n"
  instructions<-paste(instructions,paste(sprintf("%d. %s", 1:length(directions), directions),collapse="\n"),sep="<br>\n<br>")
  
  # Ingredients
  ingredients_str<-"### Ingredients\n"
  ingredients_str<-paste(ingredients_str,paste(sprintf("- [ ] %s\n", ingredients),collapse="\n"))
  
  #################writeLines(sprintf("- [ ] %s\n", 1:length(ingredients), ingredients))
  return(paste(header,instructions,ingredients_str,sep="\n"))
}
```

Column {.sidebar data-width=300}
-------------------------------------
```{r, echo=FALSE}
textInput("url","Enter URL: ")
actionButton("search", label = "Search")
```


Column
--------------------------------------
### Preface

This is a scrapping tool made to obtain recipes easily from AllRecipes.com.
---

```{r}
renderText({"Hello World"})
```


















<!-- FUTURE PLANS: Give option for advanced settings (so other sites can be used), and give option to generate PDF -->
