---
title: RECIPE SCRAPER
author: ''
date: ''
slug: recipe-scraping
categories:
  - R
tags:
  - Data Wrangling
output: 
  flexdashboard::flex_dashboard:
    logo: logo2.png
runtime: shiny

---
<script>
  $('.navbar-logo').wrap('<a href="https://stanhua.rbind.io/">');
</script>

<style>
  .tab{margin-left: 20px;
      line-height: 15%;
      }
  .navbar {
    background-color: white;
    border-color: black;
      }
  .navbar-brand {
    color: black!important;
    }
  .section.sidebar{
    background-color: #476e52;
    justify-content: flex-end;
    color: white!important;
    }
</style>


```{r setup,include=FALSE}
library(rvest)
library(shiny)
library(flexdashboard)
```

```{r, echo=FALSE}
create_text<-function(link){
  website<-function(link=link){
    webpage<-read_html(link)
    recipefor_html<-html_nodes(webpage,'.heading-content')    #change if using different website
    recipefor<-html_text(recipefor_html)
    recipefor<<-tail(recipefor,n=1)                                   #change if using different website
    
    #Fetch directions
    directions_html<-html_nodes(webpage,".instructions-section")
    directions_unparsed<-html_text(directions_html)
    directions<<-parse_block(directions_unparsed,"Step")
    
    #Fetch ingredients
    ingredients_html<-html_nodes(webpage,".ingredients-item-name")
    ingredients<<-trimws(html_text(ingredients_html))
  }
  
  #Helper Function
  parse_block<-function(str_block,separation){
    block<-trimws(str_block)
    chunks<-unlist(strsplit(block,separation))
    
    pieces<-character()
    
    for(chunk in chunks){
      unprocessed_spaces<-unlist(strsplit(chunk,"\n"))
      for(proc in unprocessed_spaces){
        line<-trimws(proc)
        if(nchar(line)>2 && line!="Advertisement"){        #note 2 is chosen arbitrarily to avoid stand-alone numbers
          pieces<-c(pieces,line)
        }
      }
    }
    pieces
  }
  
  website(link)
  
  # Recipe Title
  header<-sprintf("<h2> %s</h2>",recipefor)
  
  # Instructions
  instructions<-"<hr>\n<h3><b>Directions</h3></b>"
  instructions<-paste(instructions,"<ol>", paste(sprintf("<li> %s", directions),collapse="<br>"), "</ol>")
  
  # Ingredients
  ingredients_str<-"<hr>\n<h3><b>Ingredients</h3></b>"
  ingredients_str<-paste(ingredients_str,paste(sprintf('<p class="tab"><input type="checkbox" name="ingredient"> %s</p>', ingredients),collapse="<br>"))
  
  paste(header,instructions,ingredients_str,sep="<br>")
}
```

Column {.sidebar data-width=300}
-------------------------------------
```{r, echo=FALSE}
textInput("url",HTML("<b>Enter URL</b>:"))
actionButton("search", label = "Search")
```


Column
--------------------------------------
### **Preface**
*A scrapping tool made to obtain recipes easily from AllRecipes.com*

---
```{r}
blurb <- eventReactive(input$search,{HTML(create_text(input$url))})

renderUI({blurb()})

```





<!-- FUTURE PLANS: Give option for advanced settings (so other sites can be used), and give option to generate PDF -->
